angular
  .module('GraphFactory', [])
  .factory('GraphFactory', graphFactory)

function graphFactory($http) {
  let mockDB = {
    users: [
      { username: 'Will B', userID: '0' },
      { username: 'Todd', userID: '1' },
      { username: 'Derrick', userID: '2' },
      { username: 'Diana', userID: '3' },
      { username: 'Jayce', userID: '4' },
      { username: 'Weylin', userID: '5' },
      { username: 'Daniel L', userID: '6' },
      { username: 'Jason', userID: '7' },
      { username: 'SteveDesk', userID: '8' },
      { username: 'Dana', userID: '9' },
      { username: 'Daniel K', userID: '10' },
      { username: 'Shawn', userID: '11' },
      { username: 'Yan', userID: '12' },
      { username: 'Simon', userID: '13' },
      { username: 'JC', userID: '14' },
      { username: 'Jared', userID: '15' },
      { username: 'Mike M', userID: '16' },
      { username: 'Mike K', userID: '17' },
      { username: 'Bryan', userID: '18' },
      { username: 'Jose', userID: '19' },
      { username: 'James', userID: '20' },
      { username: 'Kate', userID: '21' },
      { username: 'Brandon', userID: '22' },
      { username: 'Yung Mike', userID: '23' },
      { username: 'Big Mike', userID: '24' },
      { username: 'Jerry', userID: '25' },
      { username: 'Sandra', userID: '26' },
      { username: 'Victoria', userID: '27' },
      { username: 'Haley', userID: '28' },
      { username: 'Sam', userID: '29' },
      { username: 'Hira', userID: '30' },
      { username: 'Dan', userID: '30' },
      { username: 'Will Sentance', userID: '32' },
    ],
    buckets: [
      { bucket: 'Go to China', bucketID: '0' },
      { bucket: 'Go Skydiving', bucketID: '1' },
      { bucket: 'Run a Triathlon', bucketID: '2' },
      { bucket: 'Learn To Code', bucketID: '3' },
      { bucket: 'Go on a Eurotrip', bucketID: '4' },
      { bucket: 'Go on a Safari', bucketID: '5' },
      { bucket: 'Play Poker in Vegas', bucketID: '6' },
      { bucket: 'Go Wine Tasting in France', bucketID: '7' },
      { bucket: 'Learn Three Languages', bucketID: '8' },
      { bucket: 'Drive Across the Country', bucketID: '9' },
      { bucket: 'Write a Book', bucketID: '10' },
      { bucket: 'Go to the Moon', bucketID: '11' },
      { bucket: 'Fly a Plane', bucketID: '12' },
      { bucket: 'Have a Threesome', bucketID: '13' },
      { bucket: 'Compete in a Pie Eating Contest', bucketID: '14' },
      { bucket: 'Publish an App', bucketID: '15' },
      { bucket: 'Learn to Play Guitar', bucketID: '16' },
      { bucket: 'Make Love in the Ocean', bucketID: '17' },
      { bucket: 'Visit all 7 Continents', bucketID: '18' },
      { bucket: 'Go on a dog Sledding Adventure', bucketID: '19' },
      { bucket: 'Swim in a Waterfall', bucketID: '20' },
      { bucket: 'Learn Latin', bucketID: '21' },
      { bucket: 'Go to Mardi Gras', bucketID: '22' },
      { bucket: 'Go to a Haunted House', bucketID: '23' },
      { bucket: 'Visit Alcatraz', bucketID: '24' },
      { bucket: 'Pet a Penguin', bucketID: '25' },
      { bucket: 'Go to Coachella', bucketID: '26' },
      { bucket: 'Chase a Tornado', bucketID: '27' },
      { bucket: 'Visit Stonehenge', bucketID: '28' },
      { bucket: 'Have Sex at Codesmith', bucketID: '29' },
      { bucket: 'Become a Codesmith Fellow', bucketID: '30' },
      { bucket: 'Date Someone Else at Codesmith', bucketID: '31' },
    ],
    join: [
      { userID: '0', bucketID: '0' },
      { userID: '0', bucketID: '1' },
      { userID: '0', bucketID: '2' },
      { userID: '0', bucketID: '3' },
      { userID: '0', bucketID: '4' },
      { userID: '0', bucketID: '5' },
      { userID: '0', bucketID: '6' },
      { userID: '1', bucketID: '1' },
      { userID: '1', bucketID: '2' },
      { userID: '1', bucketID: '3' },
      { userID: '1', bucketID: '4' },
      { userID: '1', bucketID: '5' },
      { userID: '1', bucketID: '6' },
      { userID: '1', bucketID: '7' },
      { userID: '2', bucketID: '2' },
      { userID: '2', bucketID: '3' },
      { userID: '2', bucketID: '4' },
      { userID: '2', bucketID: '5' },
      { userID: '2', bucketID: '6' },
      { userID: '2', bucketID: '7' },
      { userID: '2', bucketID: '8' },
      { userID: '3', bucketID: '3' },
      { userID: '3', bucketID: '4' },
      { userID: '3', bucketID: '5' },
      { userID: '3', bucketID: '6' },
      { userID: '3', bucketID: '7' },
      { userID: '3', bucketID: '8' },
      { userID: '3', bucketID: '9' },
      { userID: '4', bucketID: '4' },
      { userID: '4', bucketID: '5' },
      { userID: '4', bucketID: '6' },
      { userID: '4', bucketID: '7' },
      { userID: '4', bucketID: '8' },
      { userID: '4', bucketID: '9' },
      { userID: '4', bucketID: '10' },
      { userID: '5', bucketID: '5' },
      { userID: '5', bucketID: '6' },
      { userID: '5', bucketID: '7' },
      { userID: '5', bucketID: '8' },
      { userID: '5', bucketID: '9' },
      { userID: '5', bucketID: '10' },
      { userID: '5', bucketID: '11' },
      { userID: '6', bucketID: '6' },
      { userID: '6', bucketID: '7' },
      { userID: '6', bucketID: '8' },
      { userID: '6', bucketID: '9' },
      { userID: '6', bucketID: '10' },
      { userID: '6', bucketID: '11' },
      { userID: '6', bucketID: '12' },
      { userID: '7', bucketID: '7' },
      { userID: '7', bucketID: '8' },
      { userID: '7', bucketID: '9' },
      { userID: '7', bucketID: '10' },
      { userID: '7', bucketID: '11' },
      { userID: '7', bucketID: '12' },
      { userID: '7', bucketID: '13' },
      { userID: '8', bucketID: '8' },
      { userID: '8', bucketID: '9' },
      { userID: '8', bucketID: '10' },
      { userID: '8', bucketID: '11' },
      { userID: '8', bucketID: '12' },
      { userID: '8', bucketID: '13' },
      { userID: '8', bucketID: '14' },
      { userID: '9', bucketID: '9' },
      { userID: '9', bucketID: '10' },
      { userID: '9', bucketID: '11' },
      { userID: '9', bucketID: '12' },
      { userID: '9', bucketID: '13' },
      { userID: '9', bucketID: '14' },
      { userID: '9', bucketID: '15' },
      { userID: '10', bucketID: '0' },
      { userID: '10', bucketID: '1' },
      { userID: '10', bucketID: '2' },
      { userID: '10', bucketID: '3' },
      { userID: '10', bucketID: '4' },
      { userID: '10', bucketID: '5' },
      { userID: '10', bucketID: '6' },
      { userID: '11', bucketID: '1' },
      { userID: '11', bucketID: '2' },
      { userID: '11', bucketID: '3' },
      { userID: '11', bucketID: '4' },
      { userID: '11', bucketID: '5' },
      { userID: '11', bucketID: '6' },
      { userID: '11', bucketID: '7' },
      { userID: '12', bucketID: '2' },
      { userID: '12', bucketID: '3' },
      { userID: '12', bucketID: '4' },
      { userID: '12', bucketID: '5' },
      { userID: '12', bucketID: '6' },
      { userID: '12', bucketID: '7' },
      { userID: '12', bucketID: '8' },
      { userID: '13', bucketID: '3' },
      { userID: '13', bucketID: '4' },
      { userID: '13', bucketID: '5' },
      { userID: '13', bucketID: '6' },
      { userID: '13', bucketID: '7' },
      { userID: '13', bucketID: '8' },
      { userID: '13', bucketID: '9' },
      { userID: '14', bucketID: '4' },
      { userID: '14', bucketID: '5' },
      { userID: '14', bucketID: '6' },
      { userID: '14', bucketID: '7' },
      { userID: '14', bucketID: '8' },
      { userID: '14', bucketID: '9' },
      { userID: '14', bucketID: '10' },
      { userID: '15', bucketID: '5' },
      { userID: '15', bucketID: '6' },
      { userID: '15', bucketID: '7' },
      { userID: '15', bucketID: '8' },
      { userID: '15', bucketID: '9' },
      { userID: '15', bucketID: '10' },
      { userID: '15', bucketID: '11' },
      { userID: '16', bucketID: '6' },
      { userID: '16', bucketID: '7' },
      { userID: '16', bucketID: '8' },
      { userID: '16', bucketID: '9' },
      { userID: '16', bucketID: '10' },
      { userID: '16', bucketID: '11' },
      { userID: '16', bucketID: '12' },
      { userID: '17', bucketID: '7' },
      { userID: '17', bucketID: '8' },
      { userID: '17', bucketID: '9' },
      { userID: '17', bucketID: '10' },
      { userID: '17', bucketID: '11' },
      { userID: '17', bucketID: '12' },
      { userID: '17', bucketID: '13' },
      { userID: '18', bucketID: '8' },
      { userID: '18', bucketID: '9' },
      { userID: '18', bucketID: '10' },
      { userID: '18', bucketID: '11' },
      { userID: '18', bucketID: '12' },
      { userID: '18', bucketID: '13' },
      { userID: '18', bucketID: '14' },
      { userID: '19', bucketID: '9' },
      { userID: '19', bucketID: '10' },
      { userID: '19', bucketID: '11' },
      { userID: '19', bucketID: '12' },
      { userID: '19', bucketID: '13' },
      { userID: '19', bucketID: '14' },
      { userID: '19', bucketID: '15' },
      { userID: '20', bucketID: '0' },
      { userID: '20', bucketID: '1' },
      { userID: '20', bucketID: '2' },
      { userID: '20', bucketID: '3' },
      { userID: '20', bucketID: '4' },
      { userID: '20', bucketID: '5' },
      { userID: '20', bucketID: '6' },
      { userID: '21', bucketID: '1' },
      { userID: '21', bucketID: '2' },
      { userID: '21', bucketID: '3' },
      { userID: '21', bucketID: '4' },
      { userID: '21', bucketID: '5' },
      { userID: '21', bucketID: '6' },
      { userID: '21', bucketID: '7' },
      { userID: '22', bucketID: '2' },
      { userID: '22', bucketID: '3' },
      { userID: '22', bucketID: '4' },
      { userID: '22', bucketID: '5' },
      { userID: '22', bucketID: '6' },
      { userID: '22', bucketID: '7' },
      { userID: '22', bucketID: '8' },
      { userID: '23', bucketID: '3' },
      { userID: '23', bucketID: '4' },
      { userID: '23', bucketID: '5' },
      { userID: '23', bucketID: '6' },
      { userID: '23', bucketID: '7' },
      { userID: '23', bucketID: '8' },
      { userID: '23', bucketID: '9' },
      { userID: '24', bucketID: '4' },
      { userID: '24', bucketID: '5' },
      { userID: '24', bucketID: '6' },
      { userID: '24', bucketID: '7' },
      { userID: '24', bucketID: '8' },
      { userID: '24', bucketID: '9' },
      { userID: '24', bucketID: '10' },
      { userID: '25', bucketID: '5' },
      { userID: '25', bucketID: '6' },
      { userID: '25', bucketID: '7' },
      { userID: '25', bucketID: '8' },
      { userID: '25', bucketID: '9' },
      { userID: '25', bucketID: '10' },
      { userID: '25', bucketID: '11' },
      { userID: '26', bucketID: '6' },
      { userID: '26', bucketID: '7' },
      { userID: '26', bucketID: '8' },
      { userID: '26', bucketID: '9' },
      { userID: '26', bucketID: '10' },
      { userID: '26', bucketID: '11' },
      { userID: '26', bucketID: '12' },
      { userID: '27', bucketID: '7' },
      { userID: '27', bucketID: '8' },
      { userID: '27', bucketID: '9' },
      { userID: '27', bucketID: '10' },
      { userID: '27', bucketID: '11' },
      { userID: '27', bucketID: '12' },
      { userID: '27', bucketID: '13' },
      { userID: '28', bucketID: '8' },
      { userID: '28', bucketID: '9' },
      { userID: '28', bucketID: '10' },
      { userID: '28', bucketID: '11' },
      { userID: '28', bucketID: '12' },
      { userID: '28', bucketID: '13' },
      { userID: '28', bucketID: '14' },
      { userID: '29', bucketID: '9' },
      { userID: '29', bucketID: '10' },
      { userID: '29', bucketID: '11' },
      { userID: '29', bucketID: '12' },
      { userID: '29', bucketID: '13' },
      { userID: '29', bucketID: '14' },
      { userID: '29', bucketID: '15' },
      { userID: '30', bucketID: '5' },
      { userID: '30', bucketID: '6' },
      { userID: '30', bucketID: '7' },
      { userID: '30', bucketID: '8' },
      { userID: '30', bucketID: '9' },
      { userID: '30', bucketID: '10' },
      { userID: '30', bucketID: '11' },
      { userID: '31', bucketID: '6' },
      { userID: '31', bucketID: '7' },
      { userID: '31', bucketID: '8' },
      { userID: '31', bucketID: '9' },
      { userID: '31', bucketID: '10' },
      { userID: '31', bucketID: '11' },
      { userID: '31', bucketID: '12' },
      { userID: '32', bucketID: '7' },
      { userID: '32', bucketID: '8' },
      { userID: '32', bucketID: '9' },
      { userID: '32', bucketID: '10' },
      { userID: '32', bucketID: '11' },
      { userID: '32', bucketID: '12' },
      { userID: '32', bucketID: '13' },
    ],
  };
  for (let i = 0; i < mockDB.join.length; i++) {
    mockDB.join[i].bucketID = Math.floor(Math.random() * mockDB.buckets.length);
  }
  return mockDB;
}
